### ISSUE TITLE
Error reading Pixel advertisement data "Cannot initialize PixelDesignAndColor from invalid UInt8 value 114"

### ISSUE THREAD

**Issue by countchrisdo** [GameWithPixels/swift-pixels-library#7]
I created a project based on the example, imported this repo as a dependency and enabled bluetooth within it. At this point the application builds and runs without issue. However when I click the button to scan for my dice it never connects and in the debug console, I consistently get the following error messages:

> Error reading Pixel advertisement data: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "Cannot initialize PixelDesignAndColor from invalid UInt8 value 114", underlyingError: nil))

Any help would be appreciated if you've seen this error before or if you have a clue what could be wrong.

Information
- Xcode Version 16.0 (16A242d)
- Dice: d20 Hematite Grey

**Comment by obasille** [comment]
Hi @countchrisdo,
The library is a bit outdated, I will publish an update by the end of the week that address this issue and a few other things.

**Comment by jhgroenjes** [comment]
I'm getting the same error.   My new 20-side Pixels dice can't use your Swift API because of the error in the Xcode log as shown above in the title of this issue.  When will you have the new swift library updated to support the latest dice firmware?

**Comment by obasille** [comment]
Sorry the update was delayed, but here it is: 1.2.0 is now published!
